# Generated by Django 4.2.7 on 2023-11-15 04:30

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city_country_flight_location_stay_city_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload)),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stay')),
            ],
        ),
    ]
