# Generated by Django 4.2.7 on 2023-11-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_stay_property_rate_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='rate',
        ),
    ]
