# Generated by Django 4.2.7 on 2023-11-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stayorder_flightorder_carrentalorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='carrentalorder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='flightorder',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RenameField(
            model_name='flightorder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stay',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='stayorder',
            old_name='stay_id',
            new_name='stay',
        ),
        migrations.RenameField(
            model_name='stayorder',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/car'),
        ),
        migrations.AddField(
            model_name='flight',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/pics/flight'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/pics/stay')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stay')),
            ],
        ),
        migrations.CreateModel(
            name='HotelAreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stay')),
            ],
        ),
    ]
