# Generated by Django 4.2.7 on 2023-11-20 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stayorder_flightorder_carrentalorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 20, 6, 40, 29, 232667)),
        ),
        migrations.AddField(
            model_name='stay',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 6, 40, 29, 232657)),
        ),
        migrations.AddField(
            model_name='stay',
            name='stay_dict',
            field=models.JSONField(default={'Adults': 1, 'Children': 0, 'Room': 1}),
        ),
    ]
