# Generated by Django 4.2.7 on 2023-11-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_stay_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='adults',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='children',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stay',
            name='room',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
