# Generated by Django 4.2.7 on 2023-11-22 10:39

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AlterField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
    ]
