# Generated by Django 4.2.7 on 2023-11-20 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stay_end_date_stay_start_date_stay_stay_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 20, 6, 56, 52, 779030)),
        ),
        migrations.AlterField(
            model_name='stay',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 20, 6, 56, 52, 779021)),
        ),
    ]
