# Generated by Django 4.2.7 on 2023-11-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_stay_slug_image'),
        ('main', '0005_remove_location_location_alter_carrental_image_and_more'),
    ]

    operations = [
    ]
