# Generated by Django 4.2.7 on 2023-11-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20231122_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/car'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pics/stay'),
        ),
    ]
