# Generated by Django 4.2.7 on 2023-11-21 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_flight_end_city_flight_flight_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 12, 21, 13, 0, 28, 904474)),
        ),
        migrations.AlterField(
            model_name='stay',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 21, 13, 0, 28, 904457)),
        ),
    ]
