# Generated by Django 4.2.7 on 2023-11-22 12:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_carrental_image_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrental',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='flight',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.slugify_upload),
        ),
    ]
