# Generated by Django 4.2.7 on 2023-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_carrental_image_alter_flight_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stay',
            name='property_rate_stars',
        ),
        migrations.AddField(
            model_name='stay',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
