# Generated by Django 4.2.7 on 2023-11-21 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_stay_end_date_alter_stay_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='stay',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 13, 6, 55, 789845)),
        ),
        migrations.AlterField(
            model_name='stay',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 21, 13, 6, 55, 789835)),
        ),
    ]
